In [ ]:
# ============================================================
# BLOQUE 1: Preparación del entorno de trabajo
# Proyecto Final Data Mining - CASEN 2024
# ============================================================

# Librerías principales
import pandas as pd
import numpy as np
import os
import random

# Configuración general
SEED = 123
np.random.seed(SEED)
random.seed(SEED)

# Mostrar más columnas y filas en las salidas
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", lambda x: f"{x:,.3f}")

print("Librerías cargadas correctamente.")
print(f"Semilla fijada: {SEED}")

Librerías cargadas correctamente.
Semilla fijada: 123

In [ ]:
# ============================================================
# BLOQUE 2: Conexión con Google Drive y creación de carpetas
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

# Ruta principal del proyecto en Google Drive
# Puedes cambiar el nombre de la carpeta si tu grupo quiere otro.
ruta_proyecto = "/content/drive/MyDrive/DataMining_CASEN2024"

# Carpetas internas del proyecto
ruta_datos_originales = os.path.join(ruta_proyecto, "datos_originales")
ruta_datos_procesados = os.path.join(ruta_proyecto, "datos_procesados")
ruta_documentos = os.path.join(ruta_proyecto, "documentos")
ruta_salidas = os.path.join(ruta_proyecto, "salidas")

# Crear carpetas si no existen
carpetas = [
    ruta_proyecto,
    ruta_datos_originales,
    ruta_datos_procesados,
    ruta_documentos,
    ruta_salidas
]

for carpeta in carpetas:
    os.makedirs(carpeta, exist_ok=True)

print("Google Drive conectado correctamente.")
print("Carpetas del proyecto creadas o verificadas:")
for carpeta in carpetas:
    print("-", carpeta)

Mounted at /content/drive
Google Drive conectado correctamente.
Carpetas del proyecto creadas o verificadas:
- /content/drive/MyDrive/DataMining_CASEN2024
- /content/drive/MyDrive/DataMining_CASEN2024/datos_originales
- /content/drive/MyDrive/DataMining_CASEN2024/datos_procesados
- /content/drive/MyDrive/DataMining_CASEN2024/documentos
- /content/drive/MyDrive/DataMining_CASEN2024/salidas

In [ ]:
# ============================================================
# BLOQUE 3: Verificación de archivos en datos_originales
# ============================================================

# Listar archivos disponibles en la carpeta de datos originales
archivos_originales = os.listdir(ruta_datos_originales)

print("Archivos encontrados en datos_originales:")
for archivo in archivos_originales:
    print("-", archivo)

# Verificar específicamente si está la base CASEN 2024
nombre_base = "casen_2024.dta"
ruta_base_original = os.path.join(ruta_datos_originales, nombre_base)

if os.path.exists(ruta_base_original):
    print("\nBase encontrada correctamente:")
    print(ruta_base_original)
else:
    print("\nNo se encontró la base casen_2024.dta.")
    print("Revisa que el archivo esté en la carpeta datos_originales y que el nombre sea exactamente casen_2024.dta")

Archivos encontrados en datos_originales:
- casen_2024.dta

Base encontrada correctamente:
/content/drive/MyDrive/DataMining_CASEN2024/datos_originales/casen_2024.dta

In [ ]:
# ============================================================
# BLOQUE 4: Revisión inicial de la estructura de la base CASEN
# ============================================================

# Abrir la base como lector, sin cargarla completa
lector_stata = pd.read_stata(
    ruta_base_original,
    iterator=True,
    convert_categoricals=False
)

# Leer solo las primeras 5 filas
df_muestra = lector_stata.get_chunk(5)

# Obtener nombres de variables desde la muestra
variables_base = df_muestra.columns.tolist()

# Intentar obtener etiquetas/descripciones de variables
try:
    etiquetas_variables = lector_stata.variable_labels()
except:
    etiquetas_variables = {}

print("Cantidad de variables detectadas:", len(variables_base))

print("\nPrimeras 50 variables encontradas:")
for var in variables_base[:50]:
    etiqueta = etiquetas_variables.get(var, "Sin etiqueta")
    print(f"- {var}: {etiqueta}")

print("\nDimensión de la muestra cargada:", df_muestra.shape)

display(df_muestra.head())

Cantidad de variables detectadas: 877

Primeras 50 variables encontradas:
- id_vivienda: Identificación vivienda
- folio: Identificación hogar (id_vivienda hogar)
- id_persona: Identificador de la persona en el hogar
- region: Región
- region_geo: Región orden geográfico
- area: Área
- cod_upm: Código Unidad Primaria de Muestreo (UPM)
- nse: Nivel Socioeconómico de la UPM
- estrato: Estrato (comuna-área-NSE)
- hogar: Orden del hogar en la vivienda
- expr: Factor de expansión regional
- expr_osig: Factor de expansión orientación sexual e identidad de género
- varstrat: Estratos de varianza
- varunit: Conglomerados de varianza
- fecha_entrev: Fecha de la entrevista
- p1: p1. Indique tipo de acceso a la vivienda
- p2: p2. Indique estado de edificios y casas del sector
- p3: p3. Presencia de basura en el sector
- p4: p4. Vandalismo, grafiti o daño deliberado a la propiedad en el sector
- p9: p9. Incluyéndose a Ud., ¿cuántas personas viven habitualmente en la vivienda?
- p10: p10. ¿Todas las personas que viven comparten presupuesto de alimentación?
- p11: p11. Incluyendo al suyo, grupos presupuesto de alimentación separado
- tot_per_h: Total de personas en el hogar
- h1: h1. Confirmación del número de personas que viven habitualmente en el hogar
- edad: Edad
- sexo: Sexo
- pco1_a: pco1_a. Jefatura de hogar
- pco1_b: pco1_b. Relación con la jefatura de hogar
- pco1: pco1. Jefatura de hogar y relación con jefatura de hogar
- h5_cp: h5_cp. Personas que conforman parejas dentro del hogar (jefatura con pareja)
- h5_sp: h5_sp. Personas que conforman parejas dentro del hogar (jefatura sin pareja)
- h5b_1_1: h5b_1_1. Identifique y seleccione los integrantes de una pareja
- h5b_1_2: h5b_1_2. Identifique y seleccione los integrantes de una pareja
- h5a_2: h5a_2. ¿Hay más parejas en el hogar?
- h5b_2_1: h5b_2_1. Identifique y seleccione los integrantes de una pareja
- h5b_2_2: h5b_2_2. Identifique y seleccione los integrantes de una pareja
- h5a_3: h5a_3. ¿Hay más parejas en el hogar?
- h5b_3_1: h5b_3_1. Identifique y seleccione los integrantes de una pareja
- h5b_3_2: h5b_3_2. Identifique y seleccione los integrantes de una pareja
- h5a_4: h5a_4. ¿Hay más parejas en el hogar?
- h5b: h5b. Identificador de las parejas en el hogar
- ecivil: ecivil. ¿Cuál es el estado conyugal o civil actual?
- h5_10: h5_10. Actualmente, ¿vive el padre o la madre en el hogar?
- h5_1a: h5_1a. ¿Me puede indicar de quién(es) es hijo(a)?
- h5_1b: h5_1b. ¿Me puede indicar de quién(es) es hijo(a)?
- h5_20: h5_20. ¿Depende económicamente de algún integrante del hogar?
- h5_2: h5_2. ¿Me puede indicar de quién depende económicamente?
- n_nucleos: n_nucleos. Número de núcleos en el hogar
- nucleo: nucleo. Identificador del núcleo al que pertenece la persona
- pco2_a: pco2_a. Jefatura de núcleo

Dimensión de la muestra cargada: (5, 877)

,id_vivienda,folio,id_persona,region,region_geo,area,cod_upm,nse,estrato,hogar,expr,expr_osig,varstrat,varunit,fecha_entrev,p1,p2,p3,p4,p9,p10,p11,tot_per_h,h1,edad,sexo,pco1_a,pco1_b,pco1,h5_cp,h5_sp,h5b_1_1,h5b_1_2,h5a_2,h5b_2_1,h5b_2_2,h5a_3,h5b_3_1,h5b_3_2,h5a_4,h5b,ecivil,h5_10,h5_1a,h5_1b,h5_20,h5_2,n_nucleos,nucleo,pco2_a,...,hh_d_hacina_2015,hh_d_estado_2015,hh_d_habitab_2015,hh_d_servbas_2015,hh_d_medio_2015,hh_d_accesi_2015,hh_d_entorno_2015,hh_d_tsocial_2015,hh_d_seg_2015,hh_d_appart_2015,pobreza_multi_2015,disc_wg,analfabetismo,agnoesc,esc,desercion,rezagobasica,rezagomedia,asiste,educc,depen,activ,asalariado,contrato,cotiza,depen_fun,depen_grado,persona_cuidada,cuidador,lugar_nac,pueblos_indigenas,n_ocupados,n_desocupados,n_inactivos,numper,numnuc,men18c,may60c,tipohogar,tot_hog,ind_hacina,ind_san,ind_tip,ten_viv,ten_viv_f,allega_ext,allega_int,ind_mat,ind_estado,ind_cal_glob
0,1000203,100020301,1,13,7,1,10002,2,1312712,1,264,314.000,1312712,131271215,2024-12-09,1,3,3,3,2,1,NaN,2,1,62,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,1.000,2.000,NaN,2,NaN,1,1,1,...,0,0,0,0,0,0,0,1,0,0,0,1,1,12,12,NaN,NaN,NaN,2,4,NaN,3,NaN,NaN,0,0,NaN,NaN,0,0,0,0,0,2,2,1,0,1,2,1,1,1,1,1,1,0,0,1,2,1
1,1000203,100020301,2,13,7,1,10002,2,1312712,1,264,NaN,1312712,131271215,2024-12-09,1,3,3,3,2,1,NaN,2,1,92,2,0,7.000,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,2,NaN,1,1,0,...,0,0,0,0,0,0,0,1,0,0,0,1,1,6,6,NaN,NaN,NaN,2,1,NaN,3,NaN,NaN,0,0,NaN,NaN,0,0,0,0,0,2,2,1,0,1,2,1,1,1,1,1,1,0,0,1,2,1
2,1000204,100020401,1,13,7,1,10002,2,1312712,1,295,452.000,1312712,131271215,2025-01-03,1,3,3,4,4,1,NaN,4,1,61,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000,1,NaN,NaN,NaN,2,NaN,1,1,1,...,0,0,0,0,0,0,0,0,0,0,0,0,1,8,8,NaN,NaN,NaN,2,2,NaN,1,1.000,1.000,1,0,NaN,NaN,0,0,0,4,0,0,4,1,0,1,3,1,1,1,1,2,1,0,0,1,1,1
3,1000204,100020401,2,13,7,1,10002,2,1312712,1,295,NaN,1312712,131271215,2025-01-03,1,3,3,4,4,1,NaN,4,1,61,2,0,2.000,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000,1,NaN,NaN,NaN,2,NaN,1,1,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,8,8,NaN,NaN,NaN,2,2,NaN,1,1.000,1.000,1,0,NaN,NaN,0,0,0,4,0,0,4,1,0,1,3,1,1,1,1,2,1,0,0,1,1,1
4,1000204,100020401,3,13,7,1,10002,2,1312712,1,295,NaN,1312712,131271215,2025-01-03,1,3,3,4,4,1,NaN,4,1,32,1,0,4.000,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,1.000,1.000,2.000,2,NaN,1,1,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,15,15,NaN,NaN,NaN,2,6,NaN,1,1.000,1.000,1,0,NaN,NaN,0,0,0,4,0,0,4,1,0,1,3,1,1,1,1,2,1,0,0,1,1,1

In [ ]:
# ============================================================
# BLOQUE 5: Verificación de variables seleccionadas para el ETL
# ============================================================

# Variables seleccionadas inicialmente según literatura y enfoque del proyecto
variables_etl = [
    # Identificación y control
    "folio",
    "id_persona",
    "expr",
    "pco1_a",

    # Variable objetivo
    "pobreza",

    # Demografía de la jefatura
    "edad",
    "sexo",
    "ecivil",

    # Educación
    "esc",

    # Trabajo
    "activ",
    "contrato",
    "cotiza",

    # Vulnerabilidad / identidad / migración
    "disc_wg",
    "pueblos_indigenas",
    "lugar_nac",

    # Composición del hogar
    "numper",
    "tipohogar",
    "men18c",
    "may60c",

    # Situación laboral del hogar
    "n_ocupados",
    "n_desocupados",
    "n_inactivos",

    # Territorio
    "region",
    "area",

    # Vivienda
    "ind_hacina",
    "ind_san",
    "ind_mat",
    "ind_estado",
    "ind_cal_glob",
    "ten_viv_f"
]

# Verificar cuáles variables están y cuáles no están en la base
variables_presentes = [var for var in variables_etl if var in variables_base]
variables_faltantes = [var for var in variables_etl if var not in variables_base]

print("Cantidad de variables propuestas:", len(variables_etl))
print("Cantidad de variables encontradas:", len(variables_presentes))
print("Cantidad de variables faltantes:", len(variables_faltantes))

print("\nVariables encontradas:")
for var in variables_presentes:
    print("-", var)

print("\nVariables faltantes:")
if len(variables_faltantes) == 0:
    print("No hay variables faltantes. Todas las variables propuestas existen en la base.")
else:
    for var in variables_faltantes:
        print("-", var)

Cantidad de variables propuestas: 30
Cantidad de variables encontradas: 30
Cantidad de variables faltantes: 0

Variables encontradas:
- folio
- id_persona
- expr
- pco1_a
- pobreza
- edad
- sexo
- ecivil
- esc
- activ
- contrato
- cotiza
- disc_wg
- pueblos_indigenas
- lugar_nac
- numper
- tipohogar
- men18c
- may60c
- n_ocupados
- n_desocupados
- n_inactivos
- region
- area
- ind_hacina
- ind_san
- ind_mat
- ind_estado
- ind_cal_glob
- ten_viv_f

Variables faltantes:
No hay variables faltantes. Todas las variables propuestas existen en la base.

In [ ]:
# ============================================================
# BLOQUE 6: Carga de variables seleccionadas desde CASEN 2024
# ============================================================

# Cargar solo las variables seleccionadas para el proyecto
df = pd.read_stata(
    ruta_base_original,
    columns=variables_etl,
    convert_categoricals=False
)

print("Base reducida cargada correctamente.")
print("Dimensión de la base reducida:")
print(df.shape)

print("\nPrimeras filas de la base reducida:")
display(df.head())

print("\nTipos de datos:")
display(df.dtypes)

Base reducida cargada correctamente.
Dimensión de la base reducida:
(218367, 30)

Primeras filas de la base reducida:

,folio,id_persona,expr,pco1_a,pobreza,edad,sexo,ecivil,esc,activ,contrato,cotiza,disc_wg,pueblos_indigenas,lugar_nac,numper,tipohogar,men18c,may60c,n_ocupados,n_desocupados,n_inactivos,region,area,ind_hacina,ind_san,ind_mat,ind_estado,ind_cal_glob,ten_viv_f
0,100020301,1,264,1.000,3.000,62,1,8.000,12.000,3.000,NaN,0.000,1.000,0,0,2,2,0,1,0,0,2,13,1,1,1,1,2,1,1
1,100020301,2,264,0.000,3.000,92,2,7.000,6.000,3.000,NaN,0.000,1.000,0,0,2,2,0,1,0,0,2,13,1,1,1,1,2,1,1
2,100020401,1,295,1.000,3.000,61,1,1.000,8.000,1.000,1.000,1.000,0.000,0,0,4,3,0,1,4,0,0,13,1,1,1,1,1,1,1
3,100020401,2,295,0.000,3.000,61,2,1.000,8.000,1.000,1.000,1.000,0.000,0,0,4,3,0,1,4,0,0,13,1,1,1,1,1,1,1
4,100020401,3,295,0.000,3.000,32,1,8.000,15.000,1.000,1.000,1.000,0.000,0,0,4,3,0,1,4,0,0,13,1,1,1,1,1,1,1

Tipos de datos:

folio                  int32
id_persona              int8
expr                   int16
pco1_a               float64
pobreza              float64
edad                   int16
sexo                    int8
ecivil               float64
esc                  float64
activ                float64
contrato             float64
cotiza               float64
disc_wg              float64
pueblos_indigenas       int8
lugar_nac               int8
numper                  int8
tipohogar               int8
men18c                  int8
may60c                  int8
n_ocupados              int8
n_desocupados           int8
n_inactivos             int8
region                  int8
area                    int8
ind_hacina              int8
ind_san                 int8
ind_mat                 int8
ind_estado              int8
ind_cal_glob            int8
ten_viv_f               int8
dtype: object

In [ ]:
# ============================================================
# BLOQUE 7: Filtrar jefatura de hogar
# ============================================================

# Revisar distribución de la variable pco1_a
print("Distribución de pco1_a antes del filtro:")
display(df["pco1_a"].value_counts(dropna=False).sort_index())

# Filtrar solo personas que son jefatura de hogar
# Según la estructura observada, pco1_a = 1 identifica a la jefatura del hogar
df_hogares = df[df["pco1_a"] == 1].copy()

print("\nBase filtrada a nivel de hogares, usando jefatura de hogar.")
print("Dimensión antes del filtro:", df.shape)
print("Dimensión después del filtro:", df_hogares.shape)

# Verificar si queda un solo registro por hogar
duplicados_folio = df_hogares["folio"].duplicated().sum()

print("\nCantidad de folios duplicados después del filtro:", duplicados_folio)

print("\nPrimeras filas de la base filtrada:")
display(df_hogares.head())

Distribución de pco1_a antes del filtro:

pco1_a
0.000    105974
1.000     78654
NaN       33739
Name: count, dtype: int64

Base filtrada a nivel de hogares, usando jefatura de hogar.
Dimensión antes del filtro: (218367, 30)
Dimensión después del filtro: (78654, 30)

Cantidad de folios duplicados después del filtro: 0

Primeras filas de la base filtrada:

,folio,id_persona,expr,pco1_a,pobreza,edad,sexo,ecivil,esc,activ,contrato,cotiza,disc_wg,pueblos_indigenas,lugar_nac,numper,tipohogar,men18c,may60c,n_ocupados,n_desocupados,n_inactivos,region,area,ind_hacina,ind_san,ind_mat,ind_estado,ind_cal_glob,ten_viv_f
0,100020301,1,264,1.000,3.000,62,1,8.000,12.000,3.000,NaN,0.000,1.000,0,0,2,2,0,1,0,0,2,13,1,1,1,1,2,1,1
2,100020401,1,295,1.000,3.000,61,1,1.000,8.000,1.000,1.000,1.000,0.000,0,0,4,3,0,1,4,0,0,13,1,1,1,1,1,1,1
6,100020501,1,373,1.000,3.000,55,1,1.000,14.000,1.000,1.000,1.000,1.000,0,0,1,1,0,0,1,0,0,13,1,1,1,3,3,2,2
7,100020801,1,266,1.000,3.000,54,2,1.000,12.000,3.000,NaN,0.000,0.000,0,0,5,3,1,0,2,0,2,13,1,1,1,1,2,1,1
12,100070201,1,72,1.000,3.000,35,1,1.000,13.000,1.000,1.000,1.000,0.000,1,0,5,3,1,0,2,0,1,2,1,1,1,1,1,1,1

In [ ]:
# ============================================================
# BLOQUE 8: Creación de la variable objetivo pobreza_ingresos
# ============================================================

# Revisar distribución original de la variable pobreza
print("Distribución original de la variable pobreza:")
display(df_hogares["pobreza"].value_counts(dropna=False).sort_index())

print("\nProporción original de la variable pobreza:")
display((df_hogares["pobreza"].value_counts(dropna=False, normalize=True).sort_index() * 100).round(2))

# Crear variable objetivo binaria
# pobreza = 1: pobreza extrema
# pobreza = 2: pobreza no extrema
# pobreza = 3: fuera de pobreza
#
# Nueva variable:
# pobreza_ingresos = 1 si el hogar está en pobreza extrema o pobreza no extrema
# pobreza_ingresos = 0 si el hogar está fuera de pobreza

df_hogares["pobreza_ingresos"] = np.where(
    df_hogares["pobreza"].isin([1, 2]), 1,
    np.where(df_hogares["pobreza"] == 3, 0, np.nan)
)

# Revisar distribución de la nueva variable objetivo
print("\nDistribución de la variable objetivo pobreza_ingresos:")
display(df_hogares["pobreza_ingresos"].value_counts(dropna=False).sort_index())

print("\nProporción de la variable objetivo pobreza_ingresos:")
display((df_hogares["pobreza_ingresos"].value_counts(dropna=False, normalize=True).sort_index() * 100).round(2))

# Verificar cantidad de valores perdidos en la variable objetivo
nulos_objetivo = df_hogares["pobreza_ingresos"].isna().sum()

print("\nValores perdidos en pobreza_ingresos:", nulos_objetivo)

# Interpretación automática simple
prop_pobreza = df_hogares["pobreza_ingresos"].mean() * 100

print(f"\nPorcentaje de hogares clasificados en pobreza por ingresos: {prop_pobreza:.2f}%")

if prop_pobreza < 20:
    print("Advertencia: la clase pobreza parece ser minoritaria. No se debe evaluar el modelo solo con accuracy.")
else:
    print("La clase pobreza no parece extremadamente minoritaria, pero igualmente se usarán métricas complementarias.")

Distribución original de la variable pobreza:

pobreza
1.000     6369
2.000     9226
3.000    63059
Name: count, dtype: int64

Proporción original de la variable pobreza:

pobreza
1.000    8.100
2.000   11.730
3.000   80.170
Name: proportion, dtype: float64

Distribución de la variable objetivo pobreza_ingresos:

pobreza_ingresos
0.000    63059
1.000    15595
Name: count, dtype: int64

Proporción de la variable objetivo pobreza_ingresos:

pobreza_ingresos
0.000   80.170
1.000   19.830
Name: proportion, dtype: float64

Valores perdidos en pobreza_ingresos: 0

Porcentaje de hogares clasificados en pobreza por ingresos: 19.83%
Advertencia: la clase pobreza parece ser minoritaria. No se debe evaluar el modelo solo con accuracy.

In [ ]:
# ============================================================
# BLOQUE 9: Revisión de valores perdidos por variable
# ============================================================

# Calcular cantidad y porcentaje de valores perdidos
resumen_nulos = pd.DataFrame({
    "variable": df_hogares.columns,
    "n_nulos": df_hogares.isna().sum().values,
    "porcentaje_nulos": (df_hogares.isna().mean().values * 100).round(2)
})

# Ordenar de mayor a menor porcentaje de nulos
resumen_nulos = resumen_nulos.sort_values(
    by="porcentaje_nulos",
    ascending=False
).reset_index(drop=True)

print("Resumen de valores perdidos por variable:")
display(resumen_nulos)

# Separar variables según nivel de valores perdidos
variables_sin_nulos = resumen_nulos[resumen_nulos["porcentaje_nulos"] == 0]
variables_pocos_nulos = resumen_nulos[
    (resumen_nulos["porcentaje_nulos"] > 0) &
    (resumen_nulos["porcentaje_nulos"] <= 10)
]
variables_muchos_nulos = resumen_nulos[resumen_nulos["porcentaje_nulos"] > 10]

print("\nVariables sin valores perdidos:", variables_sin_nulos.shape[0])
display(variables_sin_nulos)

print("\nVariables con pocos valores perdidos, entre 0% y 10%:", variables_pocos_nulos.shape[0])
display(variables_pocos_nulos)

print("\nVariables con más de 10% de valores perdidos:", variables_muchos_nulos.shape[0])
display(variables_muchos_nulos)

Resumen de valores perdidos por variable:

             variable  n_nulos  porcentaje_nulos
0            contrato    43686            55.540
1                 esc      167             0.210
2               folio        0             0.000
3              pco1_a        0             0.000
4             pobreza        0             0.000
5          id_persona        0             0.000
6                expr        0             0.000
7                sexo        0             0.000
8                edad        0             0.000
9              ecivil        0             0.000
10              activ        0             0.000
11             cotiza        0             0.000
12            disc_wg        0             0.000
13  pueblos_indigenas        0             0.000
14          lugar_nac        0             0.000
15             numper        0             0.000
16          tipohogar        0             0.000
17             men18c        0             0.000
18             may60c        0             0.000
19         n_ocupados        0             0.000
20      n_desocupados        0             0.000
21        n_inactivos        0             0.000
22             region        0             0.000
23               area        0             0.000
24         ind_hacina        0             0.000
25            ind_san        0             0.000
26            ind_mat        0             0.000
27         ind_estado        0             0.000
28       ind_cal_glob        0             0.000
29          ten_viv_f        0             0.000
30   pobreza_ingresos        0             0.000

Variables sin valores perdidos: 29

             variable  n_nulos  porcentaje_nulos
2               folio        0             0.000
3              pco1_a        0             0.000
4             pobreza        0             0.000
5          id_persona        0             0.000
6                expr        0             0.000
7                sexo        0             0.000
8                edad        0             0.000
9              ecivil        0             0.000
10              activ        0             0.000
11             cotiza        0             0.000
12            disc_wg        0             0.000
13  pueblos_indigenas        0             0.000
14          lugar_nac        0             0.000
15             numper        0             0.000
16          tipohogar        0             0.000
17             men18c        0             0.000
18             may60c        0             0.000
19         n_ocupados        0             0.000
20      n_desocupados        0             0.000
21        n_inactivos        0             0.000
22             region        0             0.000
23               area        0             0.000
24         ind_hacina        0             0.000
25            ind_san        0             0.000
26            ind_mat        0             0.000
27         ind_estado        0             0.000
28       ind_cal_glob        0             0.000
29          ten_viv_f        0             0.000
30   pobreza_ingresos        0             0.000

Variables con pocos valores perdidos, entre 0% y 10%: 1

  variable  n_nulos  porcentaje_nulos
1      esc      167             0.210

Variables con más de 10% de valores perdidos: 1

   variable  n_nulos  porcentaje_nulos
0  contrato    43686            55.540

In [ ]:
# ============================================================
# BLOQUE 9.1: Revisión de etiquetas y categorías de variables con nulos
# ============================================================

# Abrir nuevamente la base como lector de Stata para recuperar metadatos
lector_stata = pd.read_stata(
    ruta_base_original,
    iterator=True,
    convert_categoricals=False
)

# Obtener etiquetas de variables
try:
    etiquetas_variables = lector_stata.variable_labels()
except:
    etiquetas_variables = {}

# Obtener etiquetas de valores/categorías
try:
    etiquetas_valores = lector_stata.value_labels()
except:
    etiquetas_valores = {}

# Variables que requieren revisión especial
variables_revision = ["contrato", "esc", "activ", "cotiza"]

print("Revisión de etiquetas de variables:")
for var in variables_revision:
    print("\n" + "="*60)
    print("Variable:", var)
    print("Etiqueta:", etiquetas_variables.get(var, "Sin etiqueta encontrada"))

    print("\nDistribución de valores en la base filtrada:")
    display(df_hogares[var].value_counts(dropna=False).sort_index())

print("\nDiccionarios de etiquetas de valores disponibles en la base:")
print(list(etiquetas_valores.keys())[:30])

Revisión de etiquetas de variables:

============================================================
Variable: contrato
Etiqueta: Tiene contrato de trabajo

Distribución de valores en la base filtrada:

contrato
-88.000       59
0.000       4471
1.000      30438
NaN        43686
Name: count, dtype: int64

============================================================
Variable: esc
Etiqueta: Años de escolaridad (edad >= 15)

Distribución de valores en la base filtrada:

esc
0.000      1300
1.000       606
2.000      1073
3.000      1859
4.000      2210
5.000      1675
6.000      3975
7.000      1634
8.000      7703
9.000      2240
10.000     3958
11.000     2365
12.000    22083
13.000     2372
14.000     2674
15.000     6519
16.000     3331
17.000     7845
18.000     1343
19.000      876
20.000      363
21.000      178
22.000      160
23.000       59
24.000       36
25.000       23
26.000       17
27.000        4
28.000        4
30.000        1
31.000        1
NaN         167
Name: count, dtype: int64

============================================================
Variable: activ
Etiqueta: Condición de actividad

Distribución de valores en la base filtrada:

activ
1.000    48487
2.000     2764
3.000    27403
Name: count, dtype: int64

============================================================
Variable: cotiza
Etiqueta: Cotizó durante el mes pasado

Distribución de valores en la base filtrada:

cotiza
-88.000      212
0.000      41779
1.000      36663
Name: count, dtype: int64

Diccionarios de etiquetas de valores disponibles en la base:
['ind_hacina', 'lugar_nac', 'cotiza', 'contrato', 'educc', 'desercion', 'disc_wg', 'pobreza_multi_2015', 'pobreza_severa', 'v10', 's10', 'y9', 'y8', 'y7', 'o22', 'pobreza', 'v28_aux2', 'v13', 'region', 'region_geo', 'p10', 'h1', 'pco1_a', 'pco1_b', 'pco1', 'h5_cp', 'h5_sp', 'h5a_2', 'h5a_3', 'h5a_4']

In [ ]:
# ============================================================
# BLOQUE 9.2: Revisión de etiquetas de valores y patrón de nulos
# ============================================================

# Mostrar etiquetas de valores para variables relevantes
variables_con_etiquetas = [
    "pobreza",
    "pco1_a",
    "sexo",
    "ecivil",
    "activ",
    "contrato",
    "cotiza",
    "disc_wg",
    "pueblos_indigenas",
    "lugar_nac",
    "region",
    "area",
    "ind_hacina",
    "ind_san",
    "ind_mat",
    "ind_estado",
    "ind_cal_glob",
    "ten_viv_f"
]

print("Etiquetas de categorías disponibles:")
for var in variables_con_etiquetas:
    print("\n" + "="*70)
    print("Variable:", var)

    if var in etiquetas_valores:
        print(etiquetas_valores[var])
    else:
        print("No se encontró etiqueta de valores para esta variable.")

# Revisar relación entre condición de actividad y contrato
print("\n" + "="*70)
print("Cruce entre activ y contrato:")
tabla_activ_contrato = pd.crosstab(
    df_hogares["activ"],
    df_hogares["contrato"],
    dropna=False
)
display(tabla_activ_contrato)

# Revisar relación entre condición de actividad y cotización
print("\n" + "="*70)
print("Cruce entre activ y cotiza:")
tabla_activ_cotiza = pd.crosstab(
    df_hogares["activ"],
    df_hogares["cotiza"],
    dropna=False
)
display(tabla_activ_cotiza)

# Revisar cuántos nulos de contrato hay según condición de actividad
print("\n" + "="*70)
print("Nulos de contrato según condición de actividad:")
nulos_contrato_por_activ = df_hogares.groupby("activ")["contrato"].apply(lambda x: x.isna().sum())
display(nulos_contrato_por_activ)

# Revisar nulos de esc según pobreza_ingresos
print("\n" + "="*70)
print("Nulos de esc según pobreza_ingresos:")
nulos_esc_por_pobreza = df_hogares.groupby("pobreza_ingresos")["esc"].apply(lambda x: x.isna().sum())
display(nulos_esc_por_pobreza)

Etiquetas de categorías disponibles:

======================================================================
Variable: pobreza
{np.int32(1): 'Pobreza extrema', np.int32(2): 'Pobreza no extrema', np.int32(3): 'Fuera de la pobreza'}

======================================================================
Variable: pco1_a
{np.int32(0): '0. No', np.int32(1): '1. Sí'}

======================================================================
Variable: sexo
{np.int32(1): 'Hombre', np.int32(2): 'Mujer'}

======================================================================
Variable: ecivil
{np.int32(1): '1. Casado(a)', np.int32(2): '2. Conviviente o pareja sin acuerdo de unión civil', np.int32(3): '3. Conviviente civil (con acuerdo de unión civil)', np.int32(4): '4. Anulado(a)', np.int32(5): '5. Separado(a)', np.int32(6): '6. Divorciado(a)', np.int32(7): '7. Viudo(a)', np.int32(8): '8. Soltero(a)'}

======================================================================
Variable: activ
{np.int32(1): 'Ocupados', np.int32(2): 'Desocupados', np.int32(3): 'Inactivos'}

======================================================================
Variable: contrato
{np.int32(1): 'Sí', np.int32(0): 'No', np.int32(-88): 'No sabe'}

======================================================================
Variable: cotiza
{np.int32(1): 'Sí', np.int32(0): 'No', np.int32(-88): 'No sabe'}

======================================================================
Variable: disc_wg
{np.int32(0): 'Personas sin discapacidad', np.int32(1): 'Personas con discapacidad', np.int32(-88): 'No sabe'}

======================================================================
Variable: pueblos_indigenas
{np.int32(0): 'No pertenece a pueblos indígenas', np.int32(1): 'Pertenece a pueblos indígenas', np.int32(9): 'No sabe'}

======================================================================
Variable: lugar_nac
{np.int32(1): 'Nacido(a) fuera de Chile', np.int32(0): 'Nacido(a) en Chile', np.int32(-88): 'No sabe'}

======================================================================
Variable: region
{np.int32(1): 'Región de Tarapacá', np.int32(2): 'Región de Antofagasta', np.int32(3): 'Región de Atacama', np.int32(4): 'Región de Coquimbo', np.int32(5): 'Región de Valparaíso', np.int32(6): "Región del Libertador Gral. Bernardo O'Higgins", np.int32(7): 'Región del Maule', np.int32(8): 'Región del Biobío', np.int32(9): 'Región de La Araucanía', np.int32(10): 'Región de Los Lagos', np.int32(11): 'Región de Aysén del Gral. Carlos Ibáñez del Campo', np.int32(12): 'Región de Magallanes y de la Antártica Chilena', np.int32(13): 'Región Metropolitana de Santiago', np.int32(14): 'Región de Los Ríos', np.int32(15): 'Región de Arica y Parinacota', np.int32(16): 'Región de Ñuble'}

======================================================================
Variable: area
No se encontró etiqueta de valores para esta variable.

======================================================================
Variable: ind_hacina
{np.int32(1): 'Sin hacinamiento (menos de 2,5 personas por dormitorio)', np.int32(2): 'Hacinamiento medio (entre 2,5 y 3,49 personas por dormitorio)', np.int32(3): 'Hacinamiento alto (entre 3,5 y 4,99 personas por dormitorio)', np.int32(4): 'Hacinamiento crítico (5 y más personas por dormitorio u hogar sin dormitorios de uso exclusivo)', np.int32(-88): 'No sabe'}

======================================================================
Variable: ind_san
{np.int32(1): 'Aceptable', np.int32(2): 'Deficitario', np.int32(99): 'No sabe'}

======================================================================
Variable: ind_mat
{np.int32(1): 'Vivienda Aceptable', np.int32(2): 'Vivienda Recuperable (sólo por muro)', np.int32(3): 'Vivienda Recuperable (resto)', np.int32(4): 'Vivienda Irrecuperable', np.int32(9): 'ns/nr'}

======================================================================
Variable: ind_estado
{np.int32(1): 'Bueno', np.int32(2): 'Regular', np.int32(3): 'Malo', np.int32(9): 'ns/nr'}

======================================================================
Variable: ind_cal_glob
{np.int32(1): 'Aceptable', np.int32(2): 'Recuperable', np.int32(3): 'Irrecuperable', np.int32(99): 'ns/nr'}

======================================================================
Variable: ten_viv_f
{np.int32(1): 'Tenencia formal', np.int32(2): 'Tenencia informal', np.int32(99): 'No sabe'}

======================================================================
Cruce entre activ y contrato:

contrato  -88.000  0.000    1.000    NaN
activ
1.000          59     4471    30438    13519
2.000           0        0        0     2764
3.000           0        0        0    27403

======================================================================
Cruce entre activ y cotiza:

cotiza  -88.000  0.000    1.000
activ
1.000       136    14172    34179
2.000         6     2366      392
3.000        70    25241     2092

======================================================================
Nulos de contrato según condición de actividad:

activ
1.000    13519
2.000     2764
3.000    27403
Name: contrato, dtype: int64

======================================================================
Nulos de esc según pobreza_ingresos:

pobreza_ingresos
0.000    130
1.000     37
Name: esc, dtype: int64

In [ ]:
# ============================================================
# BLOQUE 10: Tratamiento de valores faltantes y categorías especiales
# ============================================================

# Crear una copia de trabajo para limpieza
df_limpia = df_hogares.copy()

# ------------------------------------------------------------
# 1. Tratamiento de contrato
# ------------------------------------------------------------
# contrato:
# 1 = Sí
# 0 = No
# -88 = No sabe
# NaN = No aplica / sin información aplicable según flujo de encuesta
#
# Decisión: recodificar NaN como 2 = No aplica.
# No se eliminan estos registros porque representan una parte importante
# de la base y están asociados al flujo de preguntas laborales.

df_limpia["contrato"] = df_limpia["contrato"].fillna(2)

# ------------------------------------------------------------
# 2. Tratamiento de esc
# ------------------------------------------------------------
# esc: años de escolaridad.
# Tiene pocos valores perdidos, por lo que se imputa con la mediana.
# Esta decisión evita perder hogares y mantiene una imputación simple
# y reproducible para una variable numérica.

mediana_esc = df_limpia["esc"].median()
df_limpia["esc"] = df_limpia["esc"].fillna(mediana_esc)

# ------------------------------------------------------------
# 3. Verificación posterior al tratamiento
# ------------------------------------------------------------

print("Tratamiento de valores faltantes realizado.")
print(f"Mediana utilizada para imputar esc: {mediana_esc}")

print("\nValores perdidos después del tratamiento:")
display(df_limpia.isna().sum().sort_values(ascending=False))

print("\nDistribución de contrato después de recodificar NaN como 2 = No aplica:")
display(df_limpia["contrato"].value_counts(dropna=False).sort_index())

print("\nDistribución de esc después de imputación:")
display(df_limpia["esc"].describe())

Tratamiento de valores faltantes realizado.
Mediana utilizada para imputar esc: 12.0

Valores perdidos después del tratamiento:

folio                0
id_persona           0
expr                 0
pco1_a               0
pobreza              0
edad                 0
sexo                 0
ecivil               0
esc                  0
activ                0
contrato             0
cotiza               0
disc_wg              0
pueblos_indigenas    0
lugar_nac            0
numper               0
tipohogar            0
men18c               0
may60c               0
n_ocupados           0
n_desocupados        0
n_inactivos          0
region               0
area                 0
ind_hacina           0
ind_san              0
ind_mat              0
ind_estado           0
ind_cal_glob         0
ten_viv_f            0
pobreza_ingresos     0
dtype: int64

Distribución de contrato después de recodificar NaN como 2 = No aplica:

contrato
-88.000       59
0.000       4471
1.000      30438
2.000      43686
Name: count, dtype: int64

Distribución de esc después de imputación:

count   78,654.000
mean        11.274
std          4.417
min          0.000
25%          8.000
50%         12.000
75%         15.000
max         31.000
Name: esc, dtype: float64

In [ ]:
# ============================================================
# BLOQUE 11: Revisión de códigos especiales
# ============================================================

# En CASEN algunas variables usan códigos especiales como:
# -88 = No sabe
# 9   = No sabe / ns-nr en algunas variables
# 99  = No sabe / ns-nr en algunas variables
#
# Estos valores no aparecen como NaN, pero deben revisarse antes del modelamiento.

variables_codigos_especiales = [
    "contrato",
    "cotiza",
    "disc_wg",
    "pueblos_indigenas",
    "lugar_nac",
    "ind_hacina",
    "ind_san",
    "ind_mat",
    "ind_estado",
    "ind_cal_glob",
    "ten_viv_f"
]

codigos_especiales = [-88, 9, 99]

resumen_codigos_especiales = []

for var in variables_codigos_especiales:
    for codigo in codigos_especiales:
        n = (df_limpia[var] == codigo).sum()
        porcentaje = (n / len(df_limpia)) * 100

        if n > 0:
            resumen_codigos_especiales.append({
                "variable": var,
                "codigo": codigo,
                "n_casos": n,
                "porcentaje": round(porcentaje, 3)
            })

resumen_codigos_especiales = pd.DataFrame(resumen_codigos_especiales)

print("Resumen de códigos especiales encontrados:")
if resumen_codigos_especiales.empty:
    print("No se encontraron códigos especiales en las variables revisadas.")
else:
    display(resumen_codigos_especiales)

print("\nDistribución completa de variables con posibles códigos especiales:")
for var in variables_codigos_especiales:
    print("\n" + "="*60)
    print("Variable:", var)
    display(df_limpia[var].value_counts(dropna=False).sort_index())

Resumen de códigos especiales encontrados:

     variable  codigo  n_casos  porcentaje
0    contrato     -88       59       0.075
1      cotiza     -88      212       0.270
2     disc_wg     -88       11       0.014
3   lugar_nac     -88      380       0.483
4  ind_hacina     -88       21       0.027

Distribución completa de variables con posibles códigos especiales:

============================================================
Variable: contrato

contrato
-88.000       59
0.000       4471
1.000      30438
2.000      43686
Name: count, dtype: int64

============================================================
Variable: cotiza

cotiza
-88.000      212
0.000      41779
1.000      36663
Name: count, dtype: int64

============================================================
Variable: disc_wg

disc_wg
-88.000       11
0.000      66473
1.000      12170
Name: count, dtype: int64

============================================================
Variable: pueblos_indigenas

pueblos_indigenas
0    68505
1    10149
Name: count, dtype: int64

============================================================
Variable: lugar_nac

lugar_nac
-88      380
 0     73249
 1      5025
Name: count, dtype: int64

============================================================
Variable: ind_hacina

ind_hacina
-88       21
 1     75936
 2      2133
 3       338
 4       226
Name: count, dtype: int64

============================================================
Variable: ind_san

ind_san
1    73877
2     4777
Name: count, dtype: int64

============================================================
Variable: ind_mat

ind_mat
1    71037
2     2861
3     4505
4      251
Name: count, dtype: int64

============================================================
Variable: ind_estado

ind_estado
1    53300
2    16217
3     9137
Name: count, dtype: int64

============================================================
Variable: ind_cal_glob

ind_cal_glob
1    70086
2     8268
3      300
Name: count, dtype: int64

============================================================
Variable: ten_viv_f

ten_viv_f
1    61678
2    16976
Name: count, dtype: int64

In [ ]:
# ============================================================
# BLOQUE 12: Recodificación de códigos especiales
# ============================================================

# Copia de seguridad antes de recodificar códigos especiales
df_limpia_recod = df_limpia.copy()

# ------------------------------------------------------------
# Recodificación de códigos especiales "No sabe"
# ------------------------------------------------------------
# En CASEN algunas variables usan -88 para "No sabe".
# Para evitar que modelos interpreten -88 como valor numérico extremo,
# se recodifica como una categoría positiva dentro de cada variable.

# contrato:
# 0 = No
# 1 = Sí
# 2 = No aplica
# 3 = No sabe
df_limpia_recod["contrato"] = df_limpia_recod["contrato"].replace(-88, 3)

# cotiza:
# 0 = No
# 1 = Sí
# 2 = No sabe
df_limpia_recod["cotiza"] = df_limpia_recod["cotiza"].replace(-88, 2)

# disc_wg:
# 0 = Sin discapacidad
# 1 = Con discapacidad
# 2 = No sabe
df_limpia_recod["disc_wg"] = df_limpia_recod["disc_wg"].replace(-88, 2)

# lugar_nac:
# 0 = Nacido(a) en Chile
# 1 = Nacido(a) fuera de Chile
# 2 = No sabe
df_limpia_recod["lugar_nac"] = df_limpia_recod["lugar_nac"].replace(-88, 2)

# ind_hacina:
# 1 = Sin hacinamiento
# 2 = Hacinamiento medio
# 3 = Hacinamiento alto
# 4 = Hacinamiento crítico
# 5 = No sabe
df_limpia_recod["ind_hacina"] = df_limpia_recod["ind_hacina"].replace(-88, 5)

# Verificación posterior
variables_recodificadas = ["contrato", "cotiza", "disc_wg", "lugar_nac", "ind_hacina"]

print("Recodificación de códigos especiales realizada.")

for var in variables_recodificadas:
    print("\n" + "="*60)
    print("Distribución de", var, "después de recodificar:")
    display(df_limpia_recod[var].value_counts(dropna=False).sort_index())

# Verificar que ya no existan valores -88 en la base
n_menos_88 = (df_limpia_recod == -88).sum().sum()

print("\nCantidad total de valores -88 restantes en la base:", n_menos_88)

Recodificación de códigos especiales realizada.

============================================================
Distribución de contrato después de recodificar:

contrato
0.000     4471
1.000    30438
2.000    43686
3.000       59
Name: count, dtype: int64

============================================================
Distribución de cotiza después de recodificar:

cotiza
0.000    41779
1.000    36663
2.000      212
Name: count, dtype: int64

============================================================
Distribución de disc_wg después de recodificar:

disc_wg
0.000    66473
1.000    12170
2.000       11
Name: count, dtype: int64

============================================================
Distribución de lugar_nac después de recodificar:

lugar_nac
0    73249
1     5025
2      380
Name: count, dtype: int64

============================================================
Distribución de ind_hacina después de recodificar:

ind_hacina
1    75936
2     2133
3      338
4      226
5       21
Name: count, dtype: int64

Cantidad total de valores -88 restantes en la base: 0

In [ ]:
# ============================================================
# BLOQUE 13: Creación de variables nuevas justificadas
# ============================================================

# Crear una nueva copia de trabajo
df_final = df_limpia_recod.copy()

# ------------------------------------------------------------
# 1. Jefatura mujer
# ------------------------------------------------------------
# sexo:
# 1 = Hombre
# 2 = Mujer
#
# Nueva variable:
# jefatura_mujer = 1 si la jefatura es mujer
# jefatura_mujer = 0 si la jefatura es hombre

df_final["jefatura_mujer"] = np.where(df_final["sexo"] == 2, 1, 0)

# ------------------------------------------------------------
# 2. Nacido fuera de Chile
# ------------------------------------------------------------
# lugar_nac:
# 0 = Nacido(a) en Chile
# 1 = Nacido(a) fuera de Chile
# 2 = No sabe
#
# Nueva variable:
# nacido_fuera_chile = 1 si nació fuera de Chile
# nacido_fuera_chile = 0 si nació en Chile
# nacido_fuera_chile = 2 si no sabe

df_final["nacido_fuera_chile"] = df_final["lugar_nac"]

# ------------------------------------------------------------
# 3. Tasas laborales del hogar
# ------------------------------------------------------------
# Estas variables permiten comparar hogares de distinto tamaño.
# Por ejemplo, no es lo mismo tener 2 ocupados en un hogar de 2 personas
# que 2 ocupados en un hogar de 6 personas.

df_final["tasa_ocupados_hogar"] = df_final["n_ocupados"] / df_final["numper"]
df_final["tasa_desocupados_hogar"] = df_final["n_desocupados"] / df_final["numper"]
df_final["tasa_inactivos_hogar"] = df_final["n_inactivos"] / df_final["numper"]

# ------------------------------------------------------------
# 4. Verificación de variables creadas
# ------------------------------------------------------------

variables_creadas = [
    "jefatura_mujer",
    "nacido_fuera_chile",
    "tasa_ocupados_hogar",
    "tasa_desocupados_hogar",
    "tasa_inactivos_hogar"
]

print("Variables nuevas creadas correctamente:")
print(variables_creadas)

print("\nDistribución de jefatura_mujer:")
display(df_final["jefatura_mujer"].value_counts(dropna=False).sort_index())

print("\nDistribución de nacido_fuera_chile:")
display(df_final["nacido_fuera_chile"].value_counts(dropna=False).sort_index())

print("\nResumen de tasas laborales creadas:")
display(df_final[
    ["tasa_ocupados_hogar", "tasa_desocupados_hogar", "tasa_inactivos_hogar"]
].describe())

print("\nDimensión actual de la base:")
print(df_final.shape)

Variables nuevas creadas correctamente:
['jefatura_mujer', 'nacido_fuera_chile', 'tasa_ocupados_hogar', 'tasa_desocupados_hogar', 'tasa_inactivos_hogar']

Distribución de jefatura_mujer:

jefatura_mujer
0    37915
1    40739
Name: count, dtype: int64

Distribución de nacido_fuera_chile:

nacido_fuera_chile
0    73249
1     5025
2      380
Name: count, dtype: int64

Resumen de tasas laborales creadas:

       tasa_ocupados_hogar  tasa_desocupados_hogar  tasa_inactivos_hogar
count           78,654.000              78,654.000            78,654.000
mean                 0.461                   0.043                 0.379
std                  0.347                   0.142                 0.365
min                  0.000                   0.000                 0.000
25%                  0.200                   0.000                 0.000
50%                  0.500                   0.000                 0.333
75%                  0.667                   0.000                 0.667
max                  1.000                   1.000                 1.000

Dimensión actual de la base:
(78654, 36)

In [ ]:
# ============================================================
# BLOQUE 14: Selección de variables finales para la base limpia
# ============================================================

# Variables finales que se conservarán en la base limpia
variables_finales = [
    # Identificación y apoyo descriptivo
    "folio",
    "expr",

    # Variable original de pobreza y variable objetivo
    "pobreza",
    "pobreza_ingresos",

    # Características de la jefatura del hogar
    "edad",
    "jefatura_mujer",
    "ecivil",
    "esc",
    "activ",
    "contrato",
    "cotiza",
    "disc_wg",
    "pueblos_indigenas",
    "nacido_fuera_chile",

    # Composición del hogar
    "numper",
    "tipohogar",
    "men18c",
    "may60c",

    # Situación laboral del hogar
    "n_ocupados",
    "n_desocupados",
    "n_inactivos",
    "tasa_ocupados_hogar",
    "tasa_desocupados_hogar",
    "tasa_inactivos_hogar",

    # Territorio
    "region",
    "area",

    # Vivienda
    "ind_hacina",
    "ind_san",
    "ind_mat",
    "ind_estado",
    "ind_cal_glob",
    "ten_viv_f"
]

# Crear base final
df_modelo = df_final[variables_finales].copy()

print("Base final creada correctamente.")
print("Dimensión de la base final:")
print(df_modelo.shape)

print("\nPrimeras filas de la base final:")
display(df_modelo.head())

print("\nValores perdidos en la base final:")
display(df_modelo.isna().sum().sort_values(ascending=False))

print("\nVerificación de variable objetivo:")
display(df_modelo["pobreza_ingresos"].value_counts(normalize=True).mul(100).round(2))

Base final creada correctamente.
Dimensión de la base final:
(78654, 32)

Primeras filas de la base final:

,folio,expr,pobreza,pobreza_ingresos,edad,jefatura_mujer,ecivil,esc,activ,contrato,cotiza,disc_wg,pueblos_indigenas,nacido_fuera_chile,numper,tipohogar,men18c,may60c,n_ocupados,n_desocupados,n_inactivos,tasa_ocupados_hogar,tasa_desocupados_hogar,tasa_inactivos_hogar,region,area,ind_hacina,ind_san,ind_mat,ind_estado,ind_cal_glob,ten_viv_f
0,100020301,264,3.000,0.000,62,0,8.000,12.000,3.000,2.000,0.000,1.000,0,0,2,2,0,1,0,0,2,0.000,0.000,1.000,13,1,1,1,1,2,1,1
2,100020401,295,3.000,0.000,61,0,1.000,8.000,1.000,1.000,1.000,0.000,0,0,4,3,0,1,4,0,0,1.000,0.000,0.000,13,1,1,1,1,1,1,1
6,100020501,373,3.000,0.000,55,0,1.000,14.000,1.000,1.000,1.000,1.000,0,0,1,1,0,0,1,0,0,1.000,0.000,0.000,13,1,1,1,3,3,2,2
7,100020801,266,3.000,0.000,54,1,1.000,12.000,3.000,2.000,0.000,0.000,0,0,5,3,1,0,2,0,2,0.400,0.000,0.400,13,1,1,1,1,2,1,1
12,100070201,72,3.000,0.000,35,0,1.000,13.000,1.000,1.000,1.000,0.000,1,0,5,3,1,0,2,0,1,0.400,0.000,0.200,2,1,1,1,1,1,1,1

Valores perdidos en la base final:

folio                     0
expr                      0
pobreza                   0
pobreza_ingresos          0
edad                      0
jefatura_mujer            0
ecivil                    0
esc                       0
activ                     0
contrato                  0
cotiza                    0
disc_wg                   0
pueblos_indigenas         0
nacido_fuera_chile        0
numper                    0
tipohogar                 0
men18c                    0
may60c                    0
n_ocupados                0
n_desocupados             0
n_inactivos               0
tasa_ocupados_hogar       0
tasa_desocupados_hogar    0
tasa_inactivos_hogar      0
region                    0
area                      0
ind_hacina                0
ind_san                   0
ind_mat                   0
ind_estado                0
ind_cal_glob              0
ten_viv_f                 0
dtype: int64

Verificación de variable objetivo:

pobreza_ingresos
0.000   80.170
1.000   19.830
Name: proportion, dtype: float64

In [ ]:
# ============================================================
# BLOQUE 15: Separación entre base documentada y base de modelamiento
# ============================================================

# ------------------------------------------------------------
# 1. Base limpia documentada
# ------------------------------------------------------------
# Esta base conserva variables de identificación y respaldo.
# Sirve para trazabilidad, EDA y documentación del ETL.

df_limpia_documentada = df_modelo.copy()

# ------------------------------------------------------------
# 2. Base para modelamiento
# ------------------------------------------------------------
# Se eliminan variables que NO deben entrar como predictoras:
# - folio: identificador del hogar
# - expr: factor de expansión, útil para EDA pero no predictor principal
# - pobreza: variable original usada para crear pobreza_ingresos
#
# La variable pobreza_ingresos sí se conserva porque es la variable objetivo.

variables_excluir_modelo = ["folio", "expr", "pobreza"]

df_modelamiento = df_limpia_documentada.drop(columns=variables_excluir_modelo)

print("Base limpia documentada:")
print(df_limpia_documentada.shape)

print("\nBase para modelamiento:")
print(df_modelamiento.shape)

print("\nVariables excluidas del modelamiento:")
print(variables_excluir_modelo)

print("\nColumnas de la base para modelamiento:")
for col in df_modelamiento.columns:
    print("-", col)

print("\nVerificación de valores perdidos en base de modelamiento:")
display(df_modelamiento.isna().sum().sort_values(ascending=False))

print("\nDistribución de la variable objetivo en base de modelamiento:")
display(df_modelamiento["pobreza_ingresos"].value_counts(normalize=True).mul(100).round(2))

Base limpia documentada:
(78654, 32)

Base para modelamiento:
(78654, 29)

Variables excluidas del modelamiento:
['folio', 'expr', 'pobreza']

Columnas de la base para modelamiento:
- pobreza_ingresos
- edad
- jefatura_mujer
- ecivil
- esc
- activ
- contrato
- cotiza
- disc_wg
- pueblos_indigenas
- nacido_fuera_chile
- numper
- tipohogar
- men18c
- may60c
- n_ocupados
- n_desocupados
- n_inactivos
- tasa_ocupados_hogar
- tasa_desocupados_hogar
- tasa_inactivos_hogar
- region
- area
- ind_hacina
- ind_san
- ind_mat
- ind_estado
- ind_cal_glob
- ten_viv_f

Verificación de valores perdidos en base de modelamiento:

pobreza_ingresos          0
edad                      0
jefatura_mujer            0
ecivil                    0
esc                       0
activ                     0
contrato                  0
cotiza                    0
disc_wg                   0
pueblos_indigenas         0
nacido_fuera_chile        0
numper                    0
tipohogar                 0
men18c                    0
may60c                    0
n_ocupados                0
n_desocupados             0
n_inactivos               0
tasa_ocupados_hogar       0
tasa_desocupados_hogar    0
tasa_inactivos_hogar      0
region                    0
area                      0
ind_hacina                0
ind_san                   0
ind_mat                   0
ind_estado                0
ind_cal_glob              0
ten_viv_f                 0
dtype: int64

Distribución de la variable objetivo en base de modelamiento:

pobreza_ingresos
0.000   80.170
1.000   19.830
Name: proportion, dtype: float64

In [ ]:
# ============================================================
# BLOQUE 16: Validación final del ETL
# ============================================================

print("VALIDACIÓN FINAL DEL ETL")
print("="*70)

# ------------------------------------------------------------
# 1. Dimensiones finales
# ------------------------------------------------------------
print("\n1. Dimensiones finales")
print("Base limpia documentada:", df_limpia_documentada.shape)
print("Base para modelamiento:", df_modelamiento.shape)

# ------------------------------------------------------------
# 2. Verificación de duplicados
# ------------------------------------------------------------
print("\n2. Verificación de duplicados")

duplicados_documentada = df_limpia_documentada["folio"].duplicated().sum()

print("Folios duplicados en base documentada:", duplicados_documentada)

duplicados_modelamiento = df_modelamiento.duplicated().sum()
print("Filas completamente duplicadas en base de modelamiento:", duplicados_modelamiento)

# ------------------------------------------------------------
# 3. Verificación de valores perdidos
# ------------------------------------------------------------
print("\n3. Verificación de valores perdidos")

nulos_documentada = df_limpia_documentada.isna().sum().sum()
nulos_modelamiento = df_modelamiento.isna().sum().sum()

print("Total de valores perdidos en base documentada:", nulos_documentada)
print("Total de valores perdidos en base de modelamiento:", nulos_modelamiento)

# ------------------------------------------------------------
# 4. Verificación de la variable objetivo
# ------------------------------------------------------------
print("\n4. Distribución de la variable objetivo")

tabla_objetivo = pd.DataFrame({
    "frecuencia": df_modelamiento["pobreza_ingresos"].value_counts().sort_index(),
    "porcentaje": df_modelamiento["pobreza_ingresos"].value_counts(normalize=True).sort_index().mul(100).round(2)
})

display(tabla_objetivo)

# ------------------------------------------------------------
# 5. Revisión de variables numéricas
# ------------------------------------------------------------
print("\n5. Resumen de variables numéricas")

variables_numericas_revision = [
    "edad",
    "esc",
    "numper",
    "n_ocupados",
    "n_desocupados",
    "n_inactivos",
    "tasa_ocupados_hogar",
    "tasa_desocupados_hogar",
    "tasa_inactivos_hogar"
]

display(df_modelamiento[variables_numericas_revision].describe())

# ------------------------------------------------------------
# 6. Verificación de rangos de tasas laborales
# ------------------------------------------------------------
print("\n6. Verificación de rangos de tasas laborales")

tasas = [
    "tasa_ocupados_hogar",
    "tasa_desocupados_hogar",
    "tasa_inactivos_hogar"
]

for var in tasas:
    minimo = df_modelamiento[var].min()
    maximo = df_modelamiento[var].max()
    fuera_rango = ((df_modelamiento[var] < 0) | (df_modelamiento[var] > 1)).sum()

    print(f"{var}: mínimo = {minimo:.3f}, máximo = {maximo:.3f}, valores fuera de [0,1] = {fuera_rango}")

# ------------------------------------------------------------
# 7. Distribución de variables categóricas
# ------------------------------------------------------------
print("\n7. Distribución de variables categóricas principales")

variables_categoricas_revision = [
    "jefatura_mujer",
    "ecivil",
    "activ",
    "contrato",
    "cotiza",
    "disc_wg",
    "pueblos_indigenas",
    "nacido_fuera_chile",
    "tipohogar",
    "region",
    "area",
    "ind_hacina",
    "ind_san",
    "ind_mat",
    "ind_estado",
    "ind_cal_glob",
    "ten_viv_f"
]

for var in variables_categoricas_revision:
    print("\n" + "="*60)
    print("Variable:", var)
    display(df_modelamiento[var].value_counts(dropna=False).sort_index())

print("\nValidación final terminada.")

VALIDACIÓN FINAL DEL ETL
======================================================================

1. Dimensiones finales
Base limpia documentada: (78654, 32)
Base para modelamiento: (78654, 29)

2. Verificación de duplicados
Folios duplicados en base documentada: 0
Filas completamente duplicadas en base de modelamiento: 850

3. Verificación de valores perdidos
Total de valores perdidos en base documentada: 0
Total de valores perdidos en base de modelamiento: 0

4. Distribución de la variable objetivo

                  frecuencia  porcentaje
pobreza_ingresos
0.000                  63059      80.170
1.000                  15595      19.830

5. Resumen de variables numéricas

,edad,esc,numper,n_ocupados,n_desocupados,n_inactivos,tasa_ocupados_hogar,tasa_desocupados_hogar,tasa_inactivos_hogar
count,"78,654.000","78,654.000","78,654.000","78,654.000","78,654.000","78,654.000","78,654.000","78,654.000","78,654.000"
mean,54.698,11.274,2.775,1.212,0.123,0.971,0.461,0.043,0.379
std,16.268,4.417,1.461,0.922,0.369,0.924,0.347,0.142,0.365
min,16.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,42.000,8.000,2.000,1.000,0.000,0.000,0.200,0.000,0.000
50%,55.000,12.000,3.000,1.000,0.000,1.000,0.500,0.000,0.333
75%,67.000,15.000,4.000,2.000,0.000,2.000,0.667,0.000,0.667
max,103.000,31.000,19.000,9.000,5.000,9.000,1.000,1.000,1.000

6. Verificación de rangos de tasas laborales
tasa_ocupados_hogar: mínimo = 0.000, máximo = 1.000, valores fuera de [0,1] = 0
tasa_desocupados_hogar: mínimo = 0.000, máximo = 1.000, valores fuera de [0,1] = 0
tasa_inactivos_hogar: mínimo = 0.000, máximo = 1.000, valores fuera de [0,1] = 0

7. Distribución de variables categóricas principales

============================================================
Variable: jefatura_mujer

jefatura_mujer
0    37915
1    40739
Name: count, dtype: int64

============================================================
Variable: ecivil

ecivil
1.000    26818
2.000    14568
3.000      355
4.000      136
5.000     5498
6.000     4686
7.000     8354
8.000    18239
Name: count, dtype: int64

============================================================
Variable: activ

activ
1.000    48487
2.000     2764
3.000    27403
Name: count, dtype: int64

============================================================
Variable: contrato

contrato
0.000     4471
1.000    30438
2.000    43686
3.000       59
Name: count, dtype: int64

============================================================
Variable: cotiza

cotiza
0.000    41779
1.000    36663
2.000      212
Name: count, dtype: int64

============================================================
Variable: disc_wg

disc_wg
0.000    66473
1.000    12170
2.000       11
Name: count, dtype: int64

============================================================
Variable: pueblos_indigenas

pueblos_indigenas
0    68505
1    10149
Name: count, dtype: int64

============================================================
Variable: nacido_fuera_chile

nacido_fuera_chile
0    73249
1     5025
2      380
Name: count, dtype: int64

============================================================
Variable: tipohogar

tipohogar
1    15942
2    15942
3    34776
4     4993
5     5296
6     1705
Name: count, dtype: int64

============================================================
Variable: region

region
1      3093
2      3505
3      3257
4      3638
5      8415
6      5324
7      5578
8      8124
9      5458
10     4280
11     1753
12     2354
13    14151
14     3433
15     2795
16     3496
Name: count, dtype: int64

============================================================
Variable: area

area
1    64432
2    14222
Name: count, dtype: int64

============================================================
Variable: ind_hacina

ind_hacina
1    75936
2     2133
3      338
4      226
5       21
Name: count, dtype: int64

============================================================
Variable: ind_san

ind_san
1    73877
2     4777
Name: count, dtype: int64

============================================================
Variable: ind_mat

ind_mat
1    71037
2     2861
3     4505
4      251
Name: count, dtype: int64

============================================================
Variable: ind_estado

ind_estado
1    53300
2    16217
3     9137
Name: count, dtype: int64

============================================================
Variable: ind_cal_glob

ind_cal_glob
1    70086
2     8268
3      300
Name: count, dtype: int64

============================================================
Variable: ten_viv_f

ten_viv_f
1    61678
2    16976
Name: count, dtype: int64

Validación final terminada.

In [ ]:
# ============================================================
# BLOQUE 17: Guardar bases limpias del ETL
# ============================================================

# Rutas de salida
ruta_base_documentada_csv = os.path.join(
    ruta_datos_procesados,
    "casen2024_limpia_documentada.csv"
)

ruta_base_modelamiento_csv = os.path.join(
    ruta_datos_procesados,
    "casen2024_modelamiento.csv"
)

ruta_base_documentada_parquet = os.path.join(
    ruta_datos_procesados,
    "casen2024_limpia_documentada.parquet"
)

ruta_base_modelamiento_parquet = os.path.join(
    ruta_datos_procesados,
    "casen2024_modelamiento.parquet"
)

# Guardar en CSV
df_limpia_documentada.to_csv(ruta_base_documentada_csv, index=False)
df_modelamiento.to_csv(ruta_base_modelamiento_csv, index=False)

# Guardar en Parquet
# Parquet suele ser más liviano y rápido para volver a cargar en Colab.
try:
    df_limpia_documentada.to_parquet(ruta_base_documentada_parquet, index=False)
    df_modelamiento.to_parquet(ruta_base_modelamiento_parquet, index=False)
    parquet_guardado = True
except Exception as e:
    parquet_guardado = False
    print("No se pudo guardar en formato Parquet.")
    print("Error:", e)

print("Bases guardadas correctamente en CSV:")
print("-", ruta_base_documentada_csv)
print("-", ruta_base_modelamiento_csv)

if parquet_guardado:
    print("\nBases guardadas correctamente en Parquet:")
    print("-", ruta_base_documentada_parquet)
    print("-", ruta_base_modelamiento_parquet)

# Verificar tamaño de archivos guardados
print("\nTamaño de archivos guardados:")

archivos_guardados = [
    ruta_base_documentada_csv,
    ruta_base_modelamiento_csv,
    ruta_base_documentada_parquet,
    ruta_base_modelamiento_parquet
]

for archivo in archivos_guardados:
    if os.path.exists(archivo):
        tamaño_mb = os.path.getsize(archivo) / (1024**2)
        print(f"{os.path.basename(archivo)}: {tamaño_mb:.2f} MB")

Bases guardadas correctamente en CSV:
- /content/drive/MyDrive/DataMining_CASEN2024/datos_procesados/casen2024_limpia_documentada.csv
- /content/drive/MyDrive/DataMining_CASEN2024/datos_procesados/casen2024_modelamiento.csv

Bases guardadas correctamente en Parquet:
- /content/drive/MyDrive/DataMining_CASEN2024/datos_procesados/casen2024_limpia_documentada.parquet
- /content/drive/MyDrive/DataMining_CASEN2024/datos_procesados/casen2024_modelamiento.parquet

Tamaño de archivos guardados:
casen2024_limpia_documentada.csv: 7.79 MB
casen2024_modelamiento.csv: 6.50 MB
casen2024_limpia_documentada.parquet: 1.25 MB
casen2024_modelamiento.parquet: 0.67 MB